### ISSUE TITLE
Animated gifs failing with latest 6.0.1 tagged docker image

### ISSUE THREAD

**Issue by beenanner** [APSL/docker-thumbor#23]
Requesting /unsafe/300x/http://media.giphy.com/media/fLK0eUlYZoB6E/giphy-tumblr.gif causes a 500 ISE on 6.0.1 but works for 5.2.1e

Logs

```
2016-05-26 14:45:12 thumbor:ERROR [BaseHandler] get_image failed for url `http%3A//media.giphy.com/media/fLK0eUlYZoB6E/giphy-tumblr.gif`. error: `[Errno 2] No such file or directory`
2016-05-26 14:45:12 tornado.access:ERROR 500 GET /unsafe/300x/http://media.giphy.com/media/fLK0eUlYZoB6E/giphy-tumblr.gif (10.17.225.239) 679.78ms
2016-05-26 14:45:30 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 111, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 535, in _fetch
    fetch_result.buffer = self.context.request.engine.read(extension)
  File "/usr/local/lib/python2.7/site-packages/thumbor/engines/__init__.py", line 51, in read
    extension)
  File "/usr/local/lib/python2.7/site-packages/thumbor/engines/pil.py", line 238, in read_multiple
    popen = Popen(command, stdout=PIPE)
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by eduherraiz** [comment]
Ok, I can replicate the problem.
It's not a problem with the URL enconding because:
/unsafe/500x100/media.giphy.com/media/fLK0eUlYZoB6E/giphy-tumblr.gif
fails too.

I will investigate it, thanks for report.

**Comment by beenanner** [comment]
@eduherraiz no problem I'll try to dig in as well, but my python-fu is pretty weak. :-)

**Comment by kkopachev** [comment]
Looks like gifsicle is required. https://github.com/thumbor/thumbor/blob/master/thumbor/engines/pil.py#L234-L239

**Comment by beenanner** [comment]
Thanks @kkopachev I confirmed installing gifsicle fixes the issue @eduherraiz. I'll open a pull-request to add gifsicle.

**Comment by beenanner** [comment]
@eduherraiz verified this works with the latest docker tag, so once tagged I think this is free to be closed.

**Comment by eduherraiz** [comment]
Thank you @kkopachev and @beenanner !!
