### ISSUE TITLE
No module named redis_storage

### ISSUE THREAD

**Issue by dijam** [APSL/docker-thumbor#45]
We get this error when we tried to use thumbor 6.x (tried in 6.1.2, 6.1.1 and 6.0.1).
We use redis for remotecv. 

This is out compose(docker cloud config)

```
loadbalancer:
  image: 'dockercloud/haproxy:1.5.3'
  deployment_strategy: high_availability
  environment:
    - BALANCE=uri
    - MODE=tcp
  expose:
    - '443'
  links:
    - nginx
  ports:
    - '80:80'
    - '1936:1936'
  restart: always
  roles:
    - global
  tags:
    - thumbor-prod
  target_num_containers: 2
nginx:
  image: 'apsl/thumbor-nginx:6.1.1'
  deployment_strategy: every_node
  links:
    - thumbor
  tags:
    - thumbor-prod
  volumes_from:
    - thumbor
thumbor:
  image: 'apsl/thumbor:6.1.1'
  deployment_strategy: every_node
  environment:
    - ALLOW_UNSAFE_URL=False
    - 'DETECTORS=[''thumbor.detectors.queued_detector.queued_complete_detector'']'
    - MAX_AGE=31556926
    - MAX_AGE_TEMP_IMAGE=84600
    - MIXED_STORAGE_DETECTOR_STORAGE=thumbor.storages.redis_storage
    - 'OPTIMIZERS=[''thumbor.optimizers.jpegtran'']'
    - REDIS_QUEUE_SERVER_DB=0
    - REDIS_QUEUE_SERVER_HOST=thumbor-redis
    - REDIS_QUEUE_SERVER_PORT=6379
    - REDIS_STORAGE_SERVER_DB=0
    - REDIS_STORAGE_SERVER_HOST=thumbor-redis
    - REDIS_STORAGE_SERVER_PORT=6379
    - RESULT_STORAGE=thumbor.result_storages.file_storage
    - RESULT_STORAGE_STORES_UNSAFE=False
    - SECURITY_KEY=something
    - STORAGE=thumbor.storages.mixed_storage
    - STORAGE_EXPIRATION_SECONDS=864000
  links:
    - thumbor-redis
  restart: always
  tags:
    - thumbor-prod
  volumes:
    - '/thumbor_store:/data/result_storage'
    - '/logs:/logs'
thumbor-redis:
  image: 'redis:latest'
  deployment_strategy: high_availability
  ports:
    - '6379'
  restart: always
  tags:
    - thumbor-prod
thumbor-remotecv:
  image: 'apsl/remotecv:6.1.1'
  deployment_strategy: every_node
  environment:
    - REDIS_DATABASE=0
    - REDIS_HOST=thumbor-redis
    - REDIS_PORT=6379
  links:
    - thumbor-redis
  restart: always
  tags:
    - thumbor-remotecv-prod
```

And this is the full error:

```
2016-09-05 13:57:52 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 211, in get_image
    self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 209, in transform
    self.context.transformer.transform(after_transform_cb)
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 102, in transform
    self.smart_detect()
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 151, in smart_detect
    self.do_smart_detection().result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 174, in do_smart_detection
    focal_points = yield gen.maybe_future(self.context.modules.storage.get_detector_data(self.smart_storage_key))
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/site-packages/thumbor/storages/mixed_storage.py", line 73, in get_detector_data
    self._init_detector_storage()
  File "/usr/local/lib/python2.7/site-packages/thumbor/storages/mixed_storage.py", line 48, in _init_detector_storage
    class_name='Storage'
  File "/usr/local/lib/python2.7/site-packages/thumbor/importer.py", line 95, in import_item
    module = self.import_class('%s.%s' % (conf_value, class_name))
  File "/usr/local/lib/python2.7/site-packages/thumbor/importer.py", line 43, in import_class
    return import_class(name, get_module)
  File "/usr/local/lib/python2.7/site-packages/thumbor/importer.py", line 19, in import_class
    module = get_module and __import__(name) or __import__(module_name)
ImportError: No module named redis_storage
```

**Comment by dijam** [comment]
I tried locally with the config you provided in the repo: 
https://github.com/APSL/docker-thumbor/blob/master/configuration_examples/docker-compose/lazy-detector.yml

try this call: 
http://localhost/unsafe/300x303/smart/filters:quality(80)/http://static1.squarespace.com/static/54e7ac67e4b08db9da80620d/t/558b044ce4b0a7d87c0fb840/1435173997026/1500w/IMG_0399%20(1).JPG

but when remove smart it works: 
http://localhost/unsafe/300x303/filters:quality(80)/http://static1.squarespace.com/static/54e7ac67e4b08db9da80620d/t/558b044ce4b0a7d87c0fb840/1435173997026/1500w/IMG_0399%20(1).JPG

**Comment by dijam** [comment]
We did an investigation and we think it is related to the redis module change from 5 to 6. 
Here (https://github.com/APSL/docker-thumbor/blob/master/thumbor/requirements.txt) you added:
tc-redis and tc-mongo. Both of them are tc_redis and tc_mongo.

**Comment by dijam** [comment]
So it was our bad :D We thought we read the documentation well but we didn't!
The confusion came from the part in thumbor env variables: `MIXED_STORAGE_DETECTOR_STORAGE=thumbor.storages.redis_storage` 
In thumbor-docker documentation, it says the exact but in thumbor-redis docker repo, it says the correct settings that is: `MIXED_STORAGE_DETECTOR_STORAGE=tc_redis.storages.redis_storage`
Maybe can update the main repo with the changes happened there. 

I close this issue as it is not any problem with the repo besides the documentation.
Sorry for the bothering.
Cheers.
