### ISSUE TITLE
S3 results storage fails with smart detector

### ISSUE THREAD

**Issue by paulwilton** [APSL/docker-thumbor#48]
When using S3 results storage, requests fail with smart detectors 
It may well be the same issue as this:
https://github.com/thumbor/thumbor/issues/721
https://github.com/thumbor/thumbor/pull/722

Error:

```
Exception: DummyFuture does not support blocking for results
2016-10-08 19:44:39 thumbor:WARNING [AwsStorage] s3 key not found at images/zwhvs1hkqj57.detectors.txt
2016-10-08 19:45:09 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 211, in get_image
    self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 209, in transform
    self.context.transformer.transform(after_transform_cb)
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 102, in transform
    self.smart_detect()
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 151, in smart_detect
    self.do_smart_detection().result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    self._check_done()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 316, in _check_done
    raise Exception("DummyFuture does not support blocking for results")
Exception: DummyFuture does not support blocking for results
```

Env Config:

```
              environment:
                - LOADER=tc_aws.loaders.s3_loader
                - STORAGE=tc_aws.storages.s3_storage
                - DETECTORS=['thumbor.detectors.feature_detector','thumbor.detectors.face_detector']
                - AWS_ACCESS_KEY_ID=XXXXXXX
                - AWS_SECRET_ACCESS_KEY=YYYYYYYY
                - TC_AWS_REGION=us-west-2
                - TC_AWS_STORAGE_BUCKET=my-bucket
                - TC_AWS_LOADER_BUCKET=my-bucket
                - TC_AWS_RESULT_STORAGE_BUCKET=my-bucket-results
                - TC_AWS_ALLOWED_BUCKETS=['my-bucket','my-bucket-results']
                - RESULT_STORAGE=tc_aws.result_storages.s3_storage
```

**Comment by mpilar** [comment]
For what it's worth my version with my fix (linked in #721 ) has been running well in production for a while.

**Comment by eduherraiz** [comment]
I'll include the fix if is acepted on thumbor.

**Comment by kevbaldwyn** [comment]
[This PR](https://github.com/thumbor/thumbor/pull/864) on thumbor (#864) fixes this

**Comment by kevbaldwyn** [comment]
The recent new release (6.3) for thumbor has the PR that fixes this issue.

**Comment by eduherraiz** [comment]
Ready to test in the 6.3.0 tag in the docker hub.

**Comment by paulwilton** [comment]
I have finally got round to testing this  (sorry took so long)
I am testing Thumbor 6.3.0
But it still does not work for me.  I cannot store results in an S3 bucket if using smart detectors
Thumbor logs report :

**_2017-07-12 08:01:25 thumbor:WARNING [AwsStorage] s3 key not found at images/13pw069ls8ngg.detectors.txt_**

My config is (with keys obfuscated)

```
            kob-thumbor:
              # see : https://github.com/APSL/docker-thumbor
              image: "apsl/thumbor:6.3.0"
              ports:
                - "8000:8000"
              environment:
                - SECURITY_KEY=XXXXX
                - LOADER=tc_aws.loaders.s3_loader
                - ALLOW_UNSAFE_URL='True'
                - STORAGE=tc_aws.storages.s3_storage
                - DETECTORS=['thumbor.detectors.feature_detector','thumbor.detectors.face_detector']
                - AWS_ACCESS_KEY_ID=XXXXX
                - AWS_SECRET_ACCESS_KEY=XXXXX
                - TC_AWS_REGION=us-west-2
                - TC_AWS_STORAGE_BUCKET=my-storage-bucket
                - TC_AWS_LOADER_BUCKET=my-storage-bucket
                - TC_AWS_RESULT_STORAGE_BUCKET=my-results-bucket
                - TC_AWS_ALLOWED_BUCKETS=['my-storage-bucket','my-results-bucket']
                - UPLOAD_PHOTO_STORAGE=tc_aws.storages.s3_storage
                - RESULT_STORAGE=tc_aws.result_storages.s3_storage
```

**Comment by paulwilton** [comment]
Note, I dont get the same error message as in original issue, only this warning
but no results are stored ?

**Comment by paulwilton** [comment]
Yay! I can confirm it does work ok now. I was missing a setting:
- RESULT_STORAGE_STORES_UNSAFE=True
everything now working as expected 👍
