### ISSUE TITLE
"ValueError: unrecognized raw mode" in GIF

### ISSUE THREAD

**Issue by allafa70** [APSL/docker-thumbor#51]
Hi,
if I try to resize an animated gif using the thumborize.me service the image is resized perfectly
http://thumbor.thumborize.me/unsafe/150x100/https://secure.static.tumblr.com/b2a7fc9c77aed0ede4c1abd070872f96/vsbwkai/gZEnpmdmk/tumblr_static_tumblr_static_6wanbc98p1ssco8cw88oks0wc_640.gif

If I try to resize the image using my docker-thumbor (v 6.1.5) I get the following error

```
nginx_1     | 79.16.57.198 [10/Nov/2016:15:01:31 +0000] "GET /unsafe/100x100/https://secure.static.tumblr.com/b2a7fc9c77aed0ede4c1abd070872f96/vsbwkai/gZEnpmdmk/tumblr_static_tumblr_static_6wanbc98p1ssco8cw88oks0wc_640.gif HTTP/1.1" 500 0 "-" 0.220  0.220
thumbor_1   | 2016-11-10 15:01:31 thumbor:ERROR ERROR: Traceback (most recent call last):
thumbor_1   |   File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 142, in get_image
thumbor_1   |     self.context.request.image_url
thumbor_1   |   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
thumbor_1   |     value = future.result()
thumbor_1   |   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
thumbor_1   |     raise_exc_info(self._exc_info)
thumbor_1   |   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
thumbor_1   |     yielded = self.gen.send(value)
thumbor_1   |   File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 575, in _fetch
thumbor_1   |     fetch_result.buffer = self.context.request.engine.read(extension)
thumbor_1   |   File "/usr/local/lib/python2.7/site-packages/thumbor/engines/__init__.py", line 75, in read
thumbor_1   |     extension)
thumbor_1   |   File "/usr/local/lib/python2.7/site-packages/thumbor/engines/pil.py", line 227, in read_multiple
thumbor_1   |     converted_images.append(im.convert("RGB"))
thumbor_1   |   File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 841, in convert
thumbor_1   |     self.load()
thumbor_1   |   File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 760, in load
thumbor_1   |     self.im.putpalette(*self.palette.getdata())
thumbor_1   | ValueError: unrecognized raw mode
```

Can you help me please to understand where I'm wrong?

**Comment by eduherraiz** [comment]
I think is related with this issue: https://github.com/thumbor/thumbor/issues/802
Are you tried to set USE_GIFSICLE_ENGINE = True ?
The default value is False, and gifsicle is installed in the thumbor docker image.

**Comment by allafa70** [comment]
Now it works!!!!
Thank you very much! :)

**Comment by eduherraiz** [comment]
You are welcome!
