### ISSUE TITLE
tc_aws integration seems to have broken thumbor_aws 

### ISSUE THREAD

**Issue by assembledadam** [APSL/docker-thumbor#7]
Now getting:

```
thumbor_1  | ---> Starting circus...
thumbor_1  | 2016-02-08 12:54:39 circus[1] [INFO] Starting master on pid 1
thumbor_1  | 2016-02-08 12:54:39 circus[1] [INFO] sockets started
thumbor_1  | 2016-02-08 12:54:39 circus[1] [INFO] Arbiter now waiting for commands
thumbor_1  | 2016-02-08 12:54:39 circus[1] [INFO] thumbor started
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | libdc1394 error: Failed to initialize libdc1394
thumbor_1  | 2016-02-08 12:55:02 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
thumbor_1  |     yielded = self.gen.throw(*exc_info)
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 32, in check_image
thumbor_1  |     exists = yield gen.maybe_future(self.context.modules.storage.exists(kw['image'][:self.context.config.MAX_ID_LENGTH]))
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
thumbor_1  |     value = future.result()
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
thumbor_1  |     raise_exc_info(self._exc_info)
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
thumbor_1  |     yielded = next(result)
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/thumbor/storages/mixed_storage.py", line 86, in exists
thumbor_1  |     result = yield gen.maybe_future(self.file_storage.exists(path))
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/thumbor_aws/storages/s3_storage.py", line 116, in exists
thumbor_1  |     file_key = self.storage.get_key(file_abspath)
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 192, in get_key
thumbor_1  |     key, resp = self._get_key_internal(key_name, headers, query_args_l)
thumbor_1  |   File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 230, in _get_key_internal
thumbor_1  |     response.status, response.reason, '')
thumbor_1  | S3ResponseError: S3ResponseError: 403 Forbidden
```

Nothing with my AWS permissions have changed.

**Comment by assembledadam** [comment]
I'm in the process of updating my deployment to the latest version using tc_aws configs (which works for me locally), so if it all works then this won't be an issue for me.  But if this is a genuine issue i'd recommend just removing all traces of thumbor_aws and updating the readme/changelog.

**Comment by jjborie** [comment]
I can confirm the new version with tc_aws configs works locally and on elastic beanstalk for me.

**Comment by eduherraiz** [comment]
I tried to mantain the old thumbor_aws, but suposse is silly and we have problems with this in the future.
I will remove it in the next release and will comment in the Changelog.
I'm sorry about it!

I'm currently working in the next release, tested with kubernetes and with support for tc_aws in remotecv.

**Comment by assembledadam** [comment]
I've got it working with tc_aws in prod now - if you remove it in the next release then it looks like we're all good.  Closing the issue!

Cheers
